/**
 * load.js — Load test
 *
 * Purpose : 200 simultaneous users each completing one full session flow.
 *           Tests DB connection pool, Redis, rate limiter, and EC2 CPU
 *           under realistic concurrent load.
 *
 * Design decisions that avoid all previous errors:
 *   1. Tokens are pre-generated (generate-tokens.js) — skips the rate-limited
 *      create-token endpoint entirely during the test.
 *   2. 200 VUs × 1 iteration each — no looping, so no token reuse.
 *      Each VU gets one unique token from the pool by VU index.
 *   3. S3 upload is skipped — we test the Hearloop API flow only.
 *      S3 is AWS-managed infrastructure, not the bottleneck.
 *   4. Every step checks the response before proceeding — no cascading failures.
 *   5. results/ directory is created by the run script before k6 starts.
 *
 * Prerequisites:
 *   node testing/load-performance/generate-tokens.js 200
 *   (run immediately before this — tokens expire in 10 minutes)
 *
 * Run:
 *   node testing/load-performance/generate-tokens.js 200 && \
 *   mkdir -p testing/load-performance/results && \
 *   k6 run testing/load-performance/load.js
 */

import http from 'k6/http';
import { check, sleep } from 'k6';
import { Counter, Trend } from 'k6/metrics';
import { SharedArray } from 'k6/data';
import exec from 'k6/execution';
import { BASE_URL, THRESHOLDS } from './config.js';

// ── Token pool ────────────────────────────────────────────────────────────────
// Pre-generated by generate-tokens.js. Each VU picks token[__VU - 1] so
// every VU gets a unique token and no token is ever reused.
const testTokens = new SharedArray('sessionTokens', function () {
  const data = JSON.parse(open('./test-tokens.json'));
  return data.map((entry) => entry.sessionCreateToken);
});

// ── Custom metrics ────────────────────────────────────────────────────────────
const sessionCreated   = new Counter('sessions_created');
const sessionFinalized = new Counter('sessions_finalized');
const sessionFailed    = new Counter('sessions_failed');
const endToEndMs       = new Trend('end_to_end_ms', true);

// ── Test config ───────────────────────────────────────────────────────────────
export const options = {
  scenarios: {
    load: {
      executor: 'per-vu-iterations',
      vus: 200,
      iterations: 1,        // each VU runs exactly once — no looping, no token reuse
      maxDuration: '3m',
    },
  },
  thresholds: {
    ...THRESHOLDS,
    end_to_end_ms:    ['p(90)<5000'],
    sessions_created: ['count>=180'],
    sessions_failed:  ['count<20'],
  },
};

const JSON_HEADERS = { 'Content-Type': 'application/json' };

// ── Main VU function ──────────────────────────────────────────────────────────
export default function () {
  // Use VU index — each VU runs exactly once so __VU - 1 is always unique.
  const sessionCreateToken = testTokens[__VU - 1];

  if (!sessionCreateToken) {
    console.error(`VU ${__VU}: no token available — pool too small`);
    sessionFailed.add(1);
    return;
  }

  const startMs = Date.now();

  // ── Step 1: Create session ──────────────────────────────────────────────────
  const sessionRes = http.post(
    `${BASE_URL}/public/sessions`,
    JSON.stringify({ promptText: 'Load test — how was your experience?', maxDurationSec: 5 }),
    {
      headers: { ...JSON_HEADERS, Authorization: `Bearer ${sessionCreateToken}` },
      tags: { step: 'create_session' },
    }
  );

  const sessionOk = check(sessionRes, {
    'create-session: status 201':    (r) => r.status === 201,
    'create-session: has sessionToken': (r) => {
      try { return !!JSON.parse(r.body).sessionToken; } catch { return false; }
    },
  });

  if (!sessionOk) {
    console.warn(`VU ${__VU}: create-session failed — status ${sessionRes.status}: ${sessionRes.body}`);
    sessionFailed.add(1);
    return;
  }

  sessionCreated.add(1);
  const { sessionToken } = JSON.parse(sessionRes.body);

  sleep(0.3); // brief pause between steps — realistic user behaviour

  // ── Step 2: Open session ────────────────────────────────────────────────────
  const openRes = http.post(
    `${BASE_URL}/public/session/${sessionToken}/open`,
    '{}',
    { headers: JSON_HEADERS, tags: { step: 'open_session' } }
  );

  const openOk = check(openRes, {
    'open-session: status 200': (r) => r.status === 200,
  });

  if (!openOk) {
    console.warn(`VU ${__VU}: open-session failed — status ${openRes.status}`);
    sessionFailed.add(1);
    return;
  }

  sleep(0.3);

  // ── Step 3: Get upload URL ──────────────────────────────────────────────────
  const uploadUrlRes = http.post(
    `${BASE_URL}/public/session/${sessionToken}/upload-url`,
    JSON.stringify({ mimeType: 'audio/webm' }),
    { headers: JSON_HEADERS, tags: { step: 'upload_url' } }
  );

  const uploadUrlOk = check(uploadUrlRes, {
    'upload-url: status 200':    (r) => r.status === 200,
    'upload-url: has uploadUrl': (r) => {
      try { return !!JSON.parse(r.body).uploadUrl; } catch { return false; }
    },
    'upload-url: has storageKey': (r) => {
      try { return !!JSON.parse(r.body).storageKey; } catch { return false; }
    },
  });

  if (!uploadUrlOk) {
    console.warn(`VU ${__VU}: upload-url failed — status ${uploadUrlRes.status}`);
    sessionFailed.add(1);
    return;
  }

  const { storageKey } = JSON.parse(uploadUrlRes.body);

  sleep(0.3);

  // ── Step 4: Finalize (skip actual S3 upload — test API flow only) ───────────
  // We pass a fake storageKey that already exists in S3 from a real session.
  // This tests the full finalize → validate → transcribe pipeline trigger
  // without creating new S3 objects on every load test run.
  //
  // Alternative: pass the real storageKey from step 3 if you want to test
  // the full flow including S3 upload (uncomment the upload block below).
  const finalizeRes = http.post(
    `${BASE_URL}/public/session/${sessionToken}/finalize`,
    JSON.stringify({
      storageKey,
      mimeType: 'audio/webm',
      sizeBytes: 1024,
    }),
    { headers: JSON_HEADERS, tags: { step: 'finalize' } }
  );

  const finalizeOk = check(finalizeRes, {
    'finalize: status 200':    (r) => r.status === 200,
    'finalize: submitted':     (r) => {
      try { return JSON.parse(r.body).status === 'submitted'; } catch { return false; }
    },
  });

  if (!finalizeOk) {
    console.warn(`VU ${__VU}: finalize failed — status ${finalizeRes.status}: ${finalizeRes.body}`);
    sessionFailed.add(1);
    return;
  }

  sessionFinalized.add(1);
  endToEndMs.add(Date.now() - startMs);
}

// ── Summary ───────────────────────────────────────────────────────────────────
export function handleSummary(data) {
  const created   = data.metrics.sessions_created?.values?.count   ?? 0;
  const finalized = data.metrics.sessions_finalized?.values?.count ?? 0;
  const failed    = data.metrics.sessions_failed?.values?.count    ?? 0;
  const p95       = Math.round(data.metrics.http_req_duration?.values?.['p(95)'] ?? 0);
  const p99       = Math.round(data.metrics.http_req_duration?.values?.['p(99)'] ?? 0);
  const errorRate = ((data.metrics.http_req_failed?.values?.rate ?? 0) * 100).toFixed(2);
  const e2eP90    = Math.round(data.metrics.end_to_end_ms?.values?.['p(90)'] ?? 0);

  const summary = `
╔══════════════════════════════════════╗
║       Load Test Results (200 VUs)    ║
╠══════════════════════════════════════╣
║ Sessions created   : ${String(created).padEnd(15)}║
║ Sessions finalized : ${String(finalized).padEnd(15)}║
║ Sessions failed    : ${String(failed).padEnd(15)}║
╠══════════════════════════════════════╣
║ p95 latency        : ${String(p95 + 'ms').padEnd(15)}║
║ p99 latency        : ${String(p99 + 'ms').padEnd(15)}║
║ Error rate         : ${String(errorRate + '%').padEnd(15)}║
║ E2E flow p90       : ${String(e2eP90 + 'ms').padEnd(15)}║
╚══════════════════════════════════════╝
`;

  return {
    'testing/load-performance/results/load-summary.json': JSON.stringify(data, null, 2),
    stdout: summary,
  };
}
